In [1]:
from utils import read_envi_ascii
import numpy as np
from sklearn.model_selection import train_test_split
from machine_learning import DecisionTree

In [2]:
Astragalin_data_path = 'data/huangqizazhi.txt'
data = read_envi_ascii(Astragalin_data_path)
hongqi_data_path = 'data/hongqi.txt'
hongqi_data = read_envi_ascii(hongqi_data_path)

In [3]:
astragalin = data['huangqi']
zazhi1 = data['zazhi1']
zazhi2 = data['zazhi2']
background = data['background']
gancaopian = hongqi_data['gancaopian']
hongqi = hongqi_data['hongqi']

In [4]:
# 读取谱段信息
bands_file_path = 'data/Camera2_ref.txt'
with open(bands_file_path, 'rb') as f:
    bands = []
    for k in f:
        a = float(k[:-3])
        bands.append(a)
    bands = np.array(bands)

In [5]:
bands = bands[:126]

In [6]:
astragalin_y = np.ones(astragalin.shape[0]) * 0
zazhi1_y = np.ones(zazhi1.shape[0]) * 1
zazhi2_y = np.ones(zazhi2.shape[0]) * 2
background_y = np.ones(background.shape[0]) * 3
gancaopian_y = np.ones(gancaopian.shape[0]) * 4
hongqi_y = np.ones(hongqi.shape[0]) * 5

In [7]:
data_x = np.concatenate((astragalin,zazhi1,zazhi2,background,gancaopian,hongqi),axis = 0)
data_y = np.concatenate((astragalin_y,zazhi1_y,zazhi2_y,background_y,gancaopian_y,hongqi_y),axis=0)

In [8]:
train_x, test_x, train_y, test_y = train_test_split(data_x ,data_y, test_size=0.3, stratify=data_y)

In [9]:
DecisionTree(train_x, train_y,test_x, test_y)

预测时间： 0.002992391586303711
DT训练模型评分：1.0
DT待测模型评分：0.84469802393543
DT预测结果：[4. 5. 0. ... 3. 3. 2.]
---------------------------------------------------------------------------------------------------
DT分类报告：              precision    recall  f1-score   support

         0.0       0.76      0.77      0.76       615
         1.0       1.00      0.95      0.97       301
         2.0       1.00      1.00      1.00       617
         3.0       1.00      1.00      1.00       604
         4.0       0.75      0.74      0.74       735
         5.0       0.70      0.71      0.70       721

    accuracy                           0.84      3593
   macro avg       0.87      0.86      0.86      3593
weighted avg       0.85      0.84      0.85      3593

DT混淆矩阵：[[471   0   0   0  62  82]
 [  0 286   2   0   0  13]
 [  0   0 617   0   0   0]
 [  0   0   0 604   0   0]
 [ 63   0   0   0 543 129]
 [ 88   0   0   0 119 514]]
