In [1]:
from utils import read_envi_ascii
import numpy as np
from sklearn.model_selection import train_test_split
from machine_learning import DecisionTree

In [2]:
Astragalin_data_path = 'data/huangqizazhi.txt'
data = read_envi_ascii(Astragalin_data_path)
hongqi_data_path = 'data/hongqi.txt'
hongqi_data = read_envi_ascii(hongqi_data_path)

In [3]:
astragalin = data['huangqi'][:,:126]
zazhi1 = data['zazhi1'][:,:126]
zazhi2 = data['zazhi2'][:,:126]
background = data['background'][:,:126]
gancaopian = hongqi_data['gancaopian'][:,:126]
hongqi = hongqi_data['hongqi'][:,:126]

In [4]:
# 读取谱段信息
bands_file_path = 'data/Camera2_ref.txt'
with open(bands_file_path, 'rb') as f:
    bands = []
    for k in f:
        a = float(k[:-3])
        bands.append(a)
    bands = np.array(bands)

In [5]:
bands = bands[:126]

In [6]:
astragalin_y = np.ones(astragalin.shape[0]) * 0
zazhi1_y = np.ones(zazhi1.shape[0]) * 1
zazhi2_y = np.ones(zazhi2.shape[0]) * 2
background_y = np.ones(background.shape[0]) * 3
gancaopian_y = np.ones(gancaopian.shape[0]) * 4
hongqi_y = np.ones(hongqi.shape[0]) * 5

In [7]:
data_x = np.concatenate((astragalin,zazhi1,zazhi2,background,gancaopian,hongqi),axis = 0)
data_y = np.concatenate((astragalin_y,zazhi1_y,zazhi2_y,background_y,gancaopian_y,hongqi_y),axis=0)

In [9]:
train_x, test_x, train_y, test_y = train_test_split(data_x ,data_y, test_size=0.3, stratify=data_y)

In [10]:
DecisionTree(train_x, train_y,test_x, test_y)

预测时间： 0.009407281875610352
DT训练模型评分：1.0
DT待测模型评分：0.8107431116059004
DT预测结果：[0. 3. 4. ... 0. 4. 4.]
---------------------------------------------------------------------------------------------------
DT分类报告：              precision    recall  f1-score   support

         0.0       0.66      0.65      0.66       615
         1.0       0.97      0.98      0.98       301
         2.0       1.00      1.00      1.00       617
         3.0       1.00      1.00      1.00       604
         4.0       0.69      0.68      0.69       735
         5.0       0.67      0.69      0.68       721

    accuracy                           0.81      3593
   macro avg       0.83      0.83      0.83      3593
weighted avg       0.81      0.81      0.81      3593

DT混淆矩阵：[[400   0   0   0 103 112]
 [  0 295   1   0   0   5]
 [  0   2 615   0   0   0]
 [  0   0   0 604   0   0]
 [102   0   0   0 503 130]
 [100   6   0   0 119 496]]
