In [4]:
from utils import read_envi_ascii
import numpy as np
from sklearn.model_selection import train_test_split
from machine_learning import DecisionTree

In [5]:
Astragalin_data_path = 'data/hongqizazhi.txt'
data = read_envi_ascii(Astragalin_data_path)
hongqi_data_path = 'data/hongqi.txt'
hongqi_data = read_envi_ascii(hongqi_data_path)

In [6]:
astragalin = data['hongqi'][:,:126]
zazhi1 = data['zazhi1'][:,:126]
zazhi2 = data['zazhi2'][:,:126]
background = data['background'][:,:126]
gancaopian = hongqi_data['gancaopian'][:,:126]
hongqi = hongqi_data['hongqi'][:,:126]

In [7]:
# 读取谱段信息
bands_file_path = 'data/Camera2_ref.txt'
with open(bands_file_path, 'rb') as f:
    bands = []
    for k in f:
        a = float(k[:-3])
        bands.append(a)
    bands = np.array(bands)

In [8]:
bands = bands[:126]

In [9]:
astragalin_y = np.ones(astragalin.shape[0]) * 0
zazhi1_y = np.ones(zazhi1.shape[0]) * 1
zazhi2_y = np.ones(zazhi2.shape[0]) * 2
background_y = np.ones(background.shape[0]) * 3
gancaopian_y = np.ones(gancaopian.shape[0]) * 4
hongqi_y = np.ones(hongqi.shape[0]) * 5

In [10]:
data_x = np.concatenate((astragalin,zazhi1,zazhi2,background,gancaopian,hongqi),axis = 0)
data_y = np.concatenate((astragalin_y,zazhi1_y,zazhi2_y,background_y,gancaopian_y,hongqi_y),axis=0)

In [11]:
bands = [ 12,  33,  76,  78,  94, 114, 116]
data_x = data_x[:,bands]

In [12]:
train_x, test_x, train_y, test_y = train_test_split(data_x ,data_y, test_size=0.3, stratify=data_y)

In [13]:
file_name = 'models/dt.p'
DecisionTree(train_x, train_y,test_x, test_y, file_name)

预测时间： 0.0009965896606445312
DT训练模型评分：1.0
DT待测模型评分：0.8112997495129418
DT预测结果：[0. 0. 4. ... 5. 4. 1.]
---------------------------------------------------------------------------------------------------
DT分类报告：              precision    recall  f1-score   support

         0.0       0.64      0.62      0.63       615
         1.0       0.97      0.97      0.97       301
         2.0       0.99      0.99      0.99       617
         3.0       1.00      1.00      1.00       604
         4.0       0.70      0.71      0.70       735
         5.0       0.69      0.70      0.70       721

    accuracy                           0.81      3593
   macro avg       0.83      0.83      0.83      3593
weighted avg       0.81      0.81      0.81      3593

DT混淆矩阵：[[379   0   0   0 123 113]
 [  2 292   1   0   0   6]
 [  0   1 612   0   0   4]
 [  0   0   0 604   0   0]
 [108   0   0   0 520 107]
 [101   8   4   0 100 508]]
